# Postgres config using a .env file, podman secrets and IPv6 network

services:
  database:
    image: 'richard/postgres:latest'
    container_name: 'postgres_test'
    ports:
      - 5432:5432
    env_file:
      - .env 
    userns_mode: keep-id:uid=999,gid=999
    networks:
      - postgres-network
    secrets: 
      - pgsqladmin
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pgsqladmin
      - PGDATA=/var/lib/postgresql/data/testing_times
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /data/dev/postgres_setup/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5 

volumes:
  pgdata:
    driver: local 
    driver_opts:
      type: none
      device: /data/dev/volumes/postgres_data
      o: bind
    #name: 'pgdata'

networks:
  postgres-network:
    driver: bridge
    #name: 'postgres-network'

secrets:
  pgsqladmin:
    external: true
